source 'http://rubygems.org'

gem 'bundler'
gem 'chronic'
gem 'cucumber'
gem 'headless'
gem 'nokogiri'
gem 'rake'
gem 'selenium-webdriver'
gem 'syntax'
gem 'watir', '~> 6.0'
gem 'page-object'
gem 'minitest'
